name: CI

on:
  pull_request:
  push:
    tags:
      - 'v*'
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: rust-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-spelling:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo install --locked just
      - run: sudo apt-get install -y codespell
      - name: Check spelling
        run: just spelling

  formatting:
    name: Check formatting
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
        - os: macos-latest
        - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo install --locked just
      - run: rustup install nightly
      - run: rustup component add rustfmt --toolchain nightly
      - name: Check formatting
        run: just formatting

  tests:
    name: Unit tests
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
        - os: macos-latest
        - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo install --locked just
      - name: Run unit tests
        run: just tests

  deps:
    name: Check dependencies
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
        - os: macos-latest
        - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo install --locked just cargo-deny
      - name: Run dependencies check
        run: just dependencies

  lints:
    name: Clippy lints
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
        - os: macos-latest
        - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo install --locked just
      - name: Check for lints
        run: just lints
